=== DziedMaroz/UP/LogParser/data/xml/library_strict.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           targetNamespace="http://fpmi.bsu.by/lectures/java"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="library">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="book" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="author">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="title">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="publicationDate">
                                <xs:simpleType>
                                    <xs:restriction base="xs:date"/>
                                </xs:simpleType>
                            </xs:element>
                            <xs:element name="description">
                                <xs:simpleType>
                                    <xs:restriction base="xs:string">
                                        <xs:minLength value="10"/>
                                    </xs:restriction>
                                </xs:simpleType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute type="xs:string" name="id" use="required"/>
                        <xs:attribute type="xs:string" name="isbn-13" use="required"/>
                        <xs:attribute type="xs:string" name="category" use="optional"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== DziedMaroz/UP/LogParser/data/xml/library_strict.xml
<?xml version="1.0" encoding="UTF-8"?>
<library xmlns="http://fpmi.bsu.by/lectures/java" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://fpmi.bsu.by/lectures/java library_strict.xsd">
    <book id="1234" isbn-13="978-0130273635" category="Java">
        <author>Bruce Eckel</author>
        <title>Thinking in Java (2nd Edition)</title>
        <publicationDate>2000-05-31</publicationDate>
        <description>
            Thinking in Java, Second Edition is the much-anticipated revision of Bruce Eckel's best-selling
            Java introduction...
        </description>
    </book>
    <book id="5678" isbn-13="978-0201485677" category="Refactoring">
        <author>Martin Fowler</author>
        <title>Refactoring: Improving the Design of Existing Code</title>
        <publicationDate>1999-07-08</publicationDate>
        <description>
            Refactoring is about improving the design of existing code. It is the process of changing a software
            system...
        </description>
    </book>
</library>
